name: Vecna-Eve-of-Ruin
theme: jekyll-theme-midnight
title: <a href="https://kevc13.github.io/Vecna-Eve-of-Ruin/">LightningNuts vs. Vecna</a>
description: A recap of our playthrough of the Vecna Eve of Ruin campaign
