name: Vecna-Eve-of-Ruin
theme: jekyll-theme-midnight
title: [LightningNuts vs. Vecna](https://kevc13.github.io/Vecna-Eve-of-Ruin/)
description: A recap of our playthrough of the Vecna Eve of Ruin campaign
